name: Run Tests

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'tests/**'
      - 'fix/**'

jobs:
  interpreter_tests:
    runs-on: ubuntu-latest
    name: Integration Tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - run: go version

      - name: Install dependencies
        run: go mod download

      - name: Verify the dependencies
        run: go mod verify

      - name: Run tests
        run: go test -v ./...

  zen_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - engine: eval
            name: Evaluator
          - engine: vm
            name: Virtual Machine

    name: Language Tests - ${{ matrix.name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - run: go version

      - name: Install dependencies
        run: go mod download

      - name: Verify the dependencies
        run: go mod verify

      - name: Build binary
        run: go build -o zen-lang

      - name: Run Zen tests
        run: ./zen-lang test --engine ${{ matrix.engine }}
